# Generated by Django 2.1.7 on 2019-04-13 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_id', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'db_table': 'Assistants',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number_in_list', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('result', models.IntegerField()),
            ],
            options={
                'db_table': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_id', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'db_table': 'Supervisors',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('type_of_vote', models.CharField(choices=[('Election', 'Election'), ('Vote', 'Vote')], default='Election', max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('devices', models.CharField(choices=[('Phone', 'Phone'), ('Rasb', 'Rasb'), ('Phone and Rasb', 'Phone and Rasb')], default='Phone and Rasb', max_length=16)),
            ],
            options={
                'db_table': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14)),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='')),
                ('allow_phone', models.BooleanField(blank=True, null=True)),
                ('region', models.CharField(max_length=20)),
                ('user_id', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Voters',
            },
        ),
        migrations.CreateModel(
            name='VoterVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_voted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Voters_Votes',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('vote_id', models.OneToOneField(db_column='vote_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='votes.Vote')),
                ('result', models.TextField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Supervisor')),
            ],
            options={
                'db_table': 'Results',
            },
        ),
        migrations.AddField(
            model_name='votervote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Vote'),
        ),
        migrations.AddField(
            model_name='votervote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Voter'),
        ),
        migrations.AddField(
            model_name='vote',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Supervisor'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote_id',
            field=models.ForeignKey(db_column='vote_id', on_delete=django.db.models.deletion.CASCADE, to='votes.Vote'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Supervisor'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='votes',
            field=djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='votes.Vote'),
        ),
    ]
